version: "2"
linters:
  enable:
    - gosec
    - revive
  settings:
    errcheck:
      check-blank: false
  exclusions:
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    paths:
      - third_party$
      - builtin$
      - examples$
    rules:
      - path: _test\.go
        linters:
          - errcheck
formatters:
  enable:
    - gofumpt
  exclusions:
    paths:
      - third_party$
      - builtin$
      - examples$
